export default {
  0: { visualization_type: 'stick', color: '#fedcba' },
  1: { visualization_type: 'stick', color: '#abcdef' },
  2: { visualization_type: 'stick', color: '#abcdef' },
  3: { visualization_type: 'stick', color: '#abcdef' },
  4: { visualization_type: 'stick', color: '#abcdef' },
  5: { visualization_type: 'stick', color: '#abcdef' },
  6: { visualization_type: 'stick', color: '#abcdef' },
  7: { visualization_type: 'stick', color: '#fedcba' },
  8: { visualization_type: 'stick', color: '#abcdef' },
  9: { visualization_type: 'stick', color: '#abcdef' },
  10: { visualization_type: 'stick', color: '#abcdef' },
  11: { visualization_type: 'stick', color: '#abcdef' },
  12: { visualization_type: 'stick', color: '#bada55' },
  13: { visualization_type: 'stick', color: '#bada55' },
  14: { visualization_type: 'stick', color: '#bada55' },
  15: { visualization_type: 'stick', color: '#bada55' },
  16: { visualization_type: 'stick', color: '#bada55' },
  17: { visualization_type: 'stick', color: '#bada55' },
  18: { visualization_type: 'stick', color: '#bada55' },
  19: { visualization_type: 'stick', color: '#bada55' },
};
