#!/bin/bash

echo "Script Usage: script_generate_input <pdb_file_name>"

pdb_file=$1

#Create input data file
python pdbParse.py $pdb_file > data.js

#Create input stick style file
python pdbStyles.py $pdb_file > style_stick.js

#Create input style file
python pdbStyles1.py $pdb_file > style_cartoon.js

#create sphere style file
python pdbStyles2.py $pdb_file > style_sphere.js
