dashbioManhattan <- function (dataframe, chrm = "CHR", bp = "BP", p = "P",
snp = "SNP", logp = TRUE, title = "Manhattan Plot", showgrid = FALSE, xlabel = NULL, 
ylabel = "-log10(p)", point_size = 5, showlegend = FALSE,  col = c("#969696", "#252525"), 
suggestiveline_value = -log10(1e-05), suggestiveline_color = "blue", 
suggestiveline_width = 1, genomewideline_value = -log10(5e-08), genomewideline_color = "red",
genomewideline_width = 1, highlight = NULL, highlight_color = "#00FF00", ...) 
{
  manhattanly::manhattanly(x = dataframe, 
                           chr = chrm,
                           bp = bp,
                           p = p,
                           snp = snp,
                           logp = logp,
                           title = title,
                           showgrid = showgrid,
                           xlab = xlabel,
                           ylab = ylabel,
                           point_size = point_size,
                           showlegend = showlegend,
                           col = col,
                           suggestiveline = suggestiveline_value,
                           suggestiveline_color = suggestiveline_color,
                           suggestiveline_width = suggestiveline_width,
                           genomewideline = genomewideline_value,
                           genomewideline_color = genomewideline_color,
                           genomewideline_width = genomewideline_width,
                           highlight = highlight,
                           highlight_color = highlight_color,
                           ...)
}
