.dashBio_js_metadata <- function() {
deps_metadata <- list(`dash_bio` = structure(list(name = "dash_bio",
version = "0.4.5", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async~alignment.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashBio",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_bio` = structure(list(name = "dash_bio",
version = "0.4.5", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async~circos.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashBio",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_bio` = structure(list(name = "dash_bio",
version = "0.4.5", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async~ideogram.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashBio",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_bio` = structure(list(name = "dash_bio",
version = "0.4.5", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async~moleculeviewer2.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashBio",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_bio` = structure(list(name = "dash_bio",
version = "0.4.5", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async~moleculeviewer3.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashBio",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_bio` = structure(list(name = "dash_bio",
version = "0.4.5", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async~needle.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashBio",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_bio` = structure(list(name = "dash_bio",
version = "0.4.5", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async~onco.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashBio",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_bio` = structure(list(name = "dash_bio",
version = "0.4.5", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async~sequence.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashBio",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_bio` = structure(list(name = "dash_bio",
version = "0.4.5", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async~speck.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashBio",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_bio` = structure(list(name = "dash_bio",
version = "0.4.5", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async~alignment.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashBio",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_bio` = structure(list(name = "dash_bio",
version = "0.4.5", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async~circos.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashBio",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_bio` = structure(list(name = "dash_bio",
version = "0.4.5", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async~ideogram.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashBio",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_bio` = structure(list(name = "dash_bio",
version = "0.4.5", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async~moleculeviewer2.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashBio",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_bio` = structure(list(name = "dash_bio",
version = "0.4.5", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async~moleculeviewer3.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashBio",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_bio` = structure(list(name = "dash_bio",
version = "0.4.5", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async~needle.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashBio",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_bio` = structure(list(name = "dash_bio",
version = "0.4.5", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async~onco.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashBio",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_bio` = structure(list(name = "dash_bio",
version = "0.4.5", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async~sequence.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashBio",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_bio` = structure(list(name = "dash_bio",
version = "0.4.5", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async~speck.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashBio",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_bio` = structure(list(name = "dash_bio",
version = "0.4.5", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'bundle.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashBio",
all_files = FALSE), class = "html_dependency"))
return(deps_metadata)
}
